config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :attendances do
    collection do
      match 'search' => 'attendances#search', via: [:get, :post], as: :search
    end
  end
  resources :dues do
    collection do
      match 'search' => 'dues#search', via: [:get, :post], as: :search
    end
  end
  resources :lineages
  resources :events
  resources :members

  resources :calendar, only: [:show],controller: :calendar
  
  #root "members#index"
  
  get "/members/:id" , to: "members#show"
  get "/lineages/:id" , to: "lineages#show"
  resources :members, :lineages, :events
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get '/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get '/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
    get "/members/:id" , to: "members#show"
    get "/lineages/:id" , to: "lineages#show"
    root "dashboards#show"
  end

  get "/events/:id", to: "events#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lineage.rb
# frozen_string_literal: true
include ActionView::Helpers::UrlHelper
class Lineage < ApplicationRecord
  belongs_to :member
  validates :member_id, uniqueness: { scope: :member_id }
  validates :father, uniqueness: { scope: :father }
  validates :son, uniqueness: { scope: :son }
  validate :check_equality
  validate :at_least_two_nodes

  def check_equality
    errors.add(:son, ": Big and Little can't be the same") if father == son
    errors.add(:member_id, ": Little can't be the same as member id") if son == member_id
    errors.add(:member_id, ": Big can't be the same as member id") if father == member_id
  end
  
  def at_least_two_nodes
    errors.add(:Member, ': At last two members need ') if father.blank? && son.blank?
  end

  def name_check (attribute)
    if Member.where(id: attribute).exists?
      link_to(Member.where(id: attribute).last.fname, Rails.application.routes.url_helpers.member_path(attribute))
    elsif attribute == self.father
      "Head"
    else
      "Tail" 
    end 
  end

  def nil_check (attribute)
    if Member.where(id: attribute).exists?
      {}
    else
      {target: "_blank"}
    end
  end
end

app/controllers/lineages_controller.rb
# frozen_string_literal: true

class LineagesController < ApplicationController
  before_action :set_lineage, only: %i[show edit update destroy]

  # GET /lineages or /lineages.json
  def index
    @lineages = Lineage.all
  end

  # GET /lineages/1 or /lineages/1.json
  def show; end

  # GET /lineages/new
  def new
    @lineage = Lineage.new
  end

  # GET /lineages/1/edit
  def edit; end

  # POST /lineages or /lineages.json
  def create
    @lineage = Lineage.new(lineage_params)

    respond_to do |format|
      if @lineage.save
        format.html { redirect_to(lineage_url(@lineage), notice: 'Lineage was successfully created.') }
        format.json { render(:show, status: :created, location: @lineage) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @lineage.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /lineages/1 or /lineages/1.json
  def update
    respond_to do |format|
      if @lineage.update(lineage_params)
        format.html { redirect_to(lineage_url(@lineage), notice: 'Lineage was successfully updated.') }
        format.json { render(:show, status: :ok, location: @lineage) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @lineage.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /lineages/1 or /lineages/1.json
  def destroy
    @lineage.destroy!

    respond_to do |format|
      format.html { redirect_to(lineages_url, notice: 'Lineage was successfully destroyed.') }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lineage
    @lineage = Lineage.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lineage_params
    params.require(:lineage).permit(:member_id, :father, :son)
  end
end

app/helpers/lineages_helper.rb
# frozen_string_literal: true

module LineagesHelper
end

app/views/lineages/_form.html.erb
<%= form_with(model: lineage) do |form| %>
  <% if lineage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lineage.errors.count, "error") %> prohibited this lineage from being saved:</h2>

      <ul>
        <% lineage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <Label class="form-label"> <%= form.label :member_id, "Member" %> </label>
    <%= collection_select( :lineage, :member_id, Member.all, :id, :full_name, {}, { :multiple => false}) %>
  </div>

  <div class="field form-group">
    <Label class="form-label"> <%= form.label :father, "Father" %> </label>
    <%=collection_select( :lineage, :father, Member.all, :id, :full_name, include_blank: 'None') %>
  </div>

  <div class="field form-group">
    <Label class="form-label"> <%= form.label :son, "Son" %> </label>
    <%=collection_select( :lineage, :son, Member.all, :id, :full_name, include_blank: 'None') %>
  </div>

  <div class="actions">
    <%= form.submit :Submit, class:"btn btn-outline-dark" %>
  </div>
<% end %>

app/views/lineages/edit.html.erb
<% if Member.find_by(:email =>current_admin.email).admin? %>
<h1>Editing Lineage</h1>

<%= render 'form', lineage: @lineage %>

<%= link_to 'Delete', @lineage, class:"btn btn-outline-dark btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
<br><br>
<%= link_to 'Show', @lineage, class:"btn btn-outline-dark btn-sm" %>
<%= link_to 'Back', lineages_path, class:"btn btn-outline-dark btn-sm" %>
<% else %>
status: 403 'Forbidden'
<% end %>

app/views/lineages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lineages</h1>

<table>
  <thead>
    <tr>
      <th>Member</th>
      <th>Father</th>
      <th>Son</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lineages.each do |lineage| %>
      <tr>
        <td><%= link_to Member.where(id: lineage.member_id).last.fname, member_path(lineage.member_id)%></td>
        <td><%= link_to(lineage.name_check(lineage.father))%></td>
        <td><%= link_to(lineage.name_check(lineage.son))%></td>
        <td><%= link_to 'Show', lineage %></td>
        <td><%= link_to 'Edit', edit_lineage_path(lineage) %></td>
        <td><%= link_to 'Destroy', lineage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lineage', new_lineage_path %>

app/views/lineages/new.html.erb
<% if Member.find_by(:email =>current_admin.email).admin? %>
<h1>New Lineage</h1>

<%= render 'form', lineage: @lineage %>

<%= link_to 'Back to Lineage', lineages_path, class:"btn btn-outline-dark btn-sm" %>
<% else %>
status: 403 'Forbidden'
<% end %>

app/views/lineages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @lineage.member_id %>
</p>

<p>
  <strong>Father:</strong>
  <%= @lineage.father %>
</p>

<p>
  <strong>Son:</strong>
  <%= @lineage.son %>
</p>

<%= link_to 'Delete', @lineage, class:"btn btn-outline-dark btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
<br><br>
<%= link_to 'Edit', edit_lineage_path(@lineage), class:"btn btn-outline-dark btn-sm" %>
<%= link_to 'Back', lineages_path, class:"btn btn-outline-dark btn-sm" %>