config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :attendances do
    collection do
      match 'search' => 'attendances#search', via: [:get, :post], as: :search
    end
  end
  resources :dues do
    collection do
      match 'search' => 'dues#search', via: [:get, :post], as: :search
    end
  end
  resources :lineages
  resources :events
  resources :members

  resources :calendar, only: [:show],controller: :calendar
  
  #root "members#index"
  
  get "/members/:id" , to: "members#show"
  get "/lineages/:id" , to: "lineages#show"
  resources :members, :lineages, :events
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get '/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get '/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
    get "/members/:id" , to: "members#show"
    get "/lineages/:id" , to: "lineages#show"
    root "dashboards#show"
  end

  get "/events/:id", to: "events#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/due.rb
include ActionView::Helpers::UrlHelper
class Due < ApplicationRecord
    belongs_to :member
    belongs_to :event
    validates :dueAmount, presence: true
    validates :paid, inclusion: [true, false]

    def due_mail
      ar = ","
      Due.select("Distinct(member_id), dues.member_id").where(paid: 0).each do |d|
        ar += Member.where(id: d.member_id).first.email
        ar += ','
      end
      mail_to(nil, "Send Due Reminder Email", {bcc: ar, subject: "Ol'Ags Dues Reminders", class:"btn btn-outline-dark btn-sm"})
    end

    def paid_show(condtion)
      if condtion
        "\u2705"  
      else 
        "\u274C"
      end
    end
end

app/controllers/dues_controller.rb
class DuesController < ApplicationController
  before_action :set_due, only: %i[ show edit update destroy ]

  # GET /dues or /dues.json
  def index
    #@dues = Due.all
    #@members = Member.all
    #@events = Event.all
    @q = Due.ransack(params[:q])
    @dues = @q.result(distinct: true).includes(:member, :event)
  end

  def search
    index
    render :index
  end
  
  # GET /dues/1 or /dues/1.json
  def show
    @member = Member.find(@due.member_id)
    @event = Event.find(@due.event_id)
  end

  # GET /dues/new
  def new
    @due = Due.new
    @members = Member.all
    @events = Event.all
  end

  # GET /dues/1/edit
  def edit
    @members = Member.all
    @events = Event.all
  end

  # POST /dues or /dues.json
  def create
    @due = Due.new(due_params)

    respond_to do |format|
      if @due.save
        format.html { redirect_to due_url(@due), notice: "Due was successfully created." }
        format.json { render :show, status: :created, location: @due }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @due.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dues/1 or /dues/1.json
  def update
    respond_to do |format|
      if @due.update(due_params)
        format.html { redirect_to due_url(@due), notice: "Due was successfully updated." }
        format.json { render :show, status: :ok, location: @due }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @due.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dues/1 or /dues/1.json
  def destroy
    @due.destroy

    respond_to do |format|
      format.html { redirect_to dues_url, notice: "Due was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_due
      @due = Due.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def due_params
      params.require(:due).permit(:member_id, :event_id, :dueAmount, :paid)
    end
end

app/helpers/dues_helper.rb
module DuesHelper
end

app/views/dues/_form.html.erb
<%= form_with(model: due) do |form| %>
  <% if due.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(due.errors.count, "error") %> prohibited this due from being saved:</h2>

      <ul>
        <% due.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%# <Label class="form-label">Member</label> %>
    <%= form.label :member_id %>
    <%=collection_select( :due, :member_id, Member.all, :id, :full_name) %>
  </div>

  <div class="field form-group">
    <%# <Label class="form-label">Event</label> %>
    <%= form.label :event_id %>
    <%=collection_select( :due, :event_id, Event.all, :id, :name) %>
  </div>

  <div class="field form-group">
    <Label class="form-label"> <%= form.label :dueAmount, "Amount" %> </label>
    <%= form.number_field :dueAmount, :step => "0.01", class:"form-control" %>
  </div>

  <div class="field form-group">
    <Label class="form-label"> <%= form.label :paid, "Paid" %> </label>
    <%= form.check_box :paid %>
  </div>

  <div class="actions">
    <%= form.submit :Submit, class:"btn btn-outline-dark" %>
  </div>
<% end %>

app/views/dues/_search_form.html.erb
<%= search_form_for @q, url: search_dues_path,
    html: { method: :post} do |f| %>
  <div class="container">
    <div class="row justify-content-end">
      <div class="col">
        <%= f.label :member_fname_cont, "Members First Name" %>
        <%= f.search_field :member_fname_cont %>
      </div>
      <div class="col">
        <%= f.label :event_name_cont, "Event Name" %>
        <%= f.search_field :event_name_cont %>
      </div>
      <div class="col">   
        <%= f.label :paid_eq, "Paid?" %>
        <%= f.search_field :paid_eq, placeholder:"True/False" %>
      </div>
      <div class = "col">
        <%= f.submit %>
      </div>
    </div>
  </div>              
  <% end %>

app/views/dues/edit.html.erb
<% if Member.find_by(:email =>current_admin.email).admin? %>
<h1>Editing Due</h1>

<%= render 'form', due: @due %>

<%= link_to 'Delete', @due, class:"btn btn-outline-dark btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
<br><br>
<%= link_to 'Show', @due, class:"btn btn-outline-dark btn-sm" %>
<%= link_to 'Back', dues_path, class:"btn btn-outline-dark btn-sm" %>
<% else %>
status: 403 'Forbidden'
<% end %>

app/views/dues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dues</h1>
<% if Member.find_by(:email =>current_admin.email).admin? %>
  <%= Due.new.due_mail%>
  <br>
  <br>  
<%end%>
<%= render 'dues/search_form.html.erb' %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive fixed-table-body">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Member</th>
              <th>Event</th>
              <th>Due Amount</th>
              <th>Paid</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @dues.each do |due| %>
              <% if due.member_id == Member.find_by(:email => current_admin.email).id || Member.find_by(:email =>current_admin.email).admin?%>
                <tr>
                  <td><%= Member.where(id: due.member_id).last.fname %></td>
                  <td><%= Event.where(id: due.event_id).last.name %></td>
                  <td><%= due.dueAmount %></td>
                  <td><%= due.paid_show(due.paid?) %></td>
                  <% if Member.find_by(:email =>current_admin.email).admin? %>
                  <td><%= link_to 'Show', due %></td>
                  <td><%= link_to 'Edit', edit_due_path(due) %></td>
                  <td><%= link_to 'Destroy', due, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  <%end %>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<br>
<% if Member.find_by(:email =>current_admin.email).admin? %>
  <%= link_to 'New Due', new_due_path, class:"btn btn-outline-dark btn-sm" %>
  <%= link_to 'Members Page', members_path, class:"btn btn-outline-dark btn-sm" %>
  <%= link_to 'Events Page', events_path, class:"btn btn-outline-dark btn-sm" %>
<%end %>

app/views/dues/new.html.erb
<% if Member.find_by(:email =>current_admin.email).admin? %>
<h1>New Due</h1>

<%= render 'form', due: @due %>

<%= link_to 'Back to Dues', dues_path, class:"btn btn-outline-dark btn-sm" %>
<% else %>
status: 403 'Forbidden'
<% end %>

app/views/dues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @member.fname %>
</p>

<p>
  <strong>Event:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Due Amount:</strong>
  <%= @due.dueAmount %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @due.paid %>
</p>
<% if Member.find_by(:email =>current_admin.email).admin? %>
  <%= link_to 'Remove Due', @due, class:"btn btn-outline-dark btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
  <br><br>
  <%= link_to 'Edit', edit_due_path(@due), class:"btn btn-outline-dark btn-sm" %>
<%end %>
<%= link_to 'Return to Dues', dues_path, class:"btn btn-outline-dark btn-sm" %>