config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :attendances do
    collection do
      match 'search' => 'attendances#search', via: [:get, :post], as: :search
    end
  end
  resources :dues do
    collection do
      match 'search' => 'dues#search', via: [:get, :post], as: :search
    end
  end
  resources :lineages
  resources :events
  resources :members

  resources :calendar, only: [:show],controller: :calendar
  
  #root "members#index"
  
  get "/members/:id" , to: "members#show"
  get "/lineages/:id" , to: "lineages#show"
  resources :members, :lineages, :events
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get '/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get '/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
    get "/members/:id" , to: "members#show"
    get "/lineages/:id" , to: "lineages#show"
    root "dashboards#show"
  end

  get "/events/:id", to: "events#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :event 
    belongs_to :member 
    validates :attended, :rsvp, inclusion: [true, false]
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: %i[ show edit update destroy ]

  # GET /attendances or /attendances.json
  def index
    #@attendances = Attendance.all
    @members = Member.all
    @events = Event.all

    @q = Attendance.ransack(params[:q])
    @attendances = @q.result(distinct: true).includes(:member, :event)
    
  end

  def search
    index
    render :index
  end

  # GET /attendances/1 or /attendances/1.json
  def show
    @member = Member.find(@attendance.member_id)
    @event = Event.find(@attendance.event_id)
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
    @members = Member.all
    @events = Event.all
  end

  # GET /attendances/1/edit
  def edit
    @members = Member.all
    @events = Event.all
  end

  # POST /attendances or /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to attendance_url(@attendance), notice: "Attendance was successfully created." }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1 or /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to attendance_url(@attendance), notice: "Attendance was successfully updated." }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1 or /attendances/1.json
  def destroy
    @attendance.destroy

    respond_to do |format|
      format.html { redirect_to attendances_url, notice: "Attendance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.require(:attendance).permit(:member_id, :event_id, :attended, :rsvp)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_with(model: attendance) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
        <% attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <Label class="form-label"> <%= form.label :member, "Member" %> </label>
    <%=collection_select( :attendance, :member_id, Member.all, :id, :full_name) %>
  </div>

  <div class="field form-group">
    <%= form.label :event, "Event" %> </label>
    <%=collection_select( :attendance, :event_id, Event.all, :id, :name) %>
  </div>

  <div class="field form-group">
    <%= form.label :attended %>
    <%= form.check_box :attended %>
  </div>

  <div class="field form-group">
    <%= form.label :rsvp %>
    <%= form.check_box :rsvp %>
  </div>

  <div class="actions">
    <%= form.submit :Submit, class:"btn btn-outline-dark" %>
  </div>
<% end %>

app/views/attendances/_search_form.html.erb
<%= search_form_for @q, url: search_attendances_path,
    html: { method: :post} do |f| %>
    <div class="container">
    <div class="row justify-content-end">
      <div class="col">
        <%= f.label :member_fname_cont %>
        <%= f.search_field :member_fname_cont %>
      </div>
      <div class="col">
        <%= f.label :event_name_cont %>
        <%= f.search_field :event_name_cont %>
      </div>
      <div class="col">
          <%= f.label :attended_eq %>
    <%= f.search_field :attended_eq %>
      </div>
      <div class="col">    
        <%= f.label :rsvp_eq %>
        <%= f.search_field :rsvp_eq %>
      </div>
      <div class = "col">
        <%= f.submit %>
      </div>
    </div>
  </div>  
<% end %>

app/views/attendances/edit.html.erb
<% if Member.find_by(:email =>current_admin.email).admin? %>
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Delete', @attendance, class:"btn btn-outline-dark btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>\
<br><br>
<%= link_to 'Show', @attendance, class:"btn btn-outline-dark btn-sm" %> 
<%= link_to 'Back', attendances_path, class:"btn btn-outline-dark btn-sm" %>
<% else %>
status: 403 'Forbidden'
<% end %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendances</h1>

<%= render 'attendances/search_form.html.erb' %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive fixed-table-body">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Member</th>
              <th>Event</th>
              <th>Attended</th>
              <th>Rsvp</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @attendances.each do |attendance| %>
            <% if attendance.member_id == Member.find_by(:email => current_admin.email).id || Member.find_by(:email =>current_admin.email).admin?%>
              <tr>
                <td><%= Member.where(id: attendance.member_id).last.fname %></td>
                <td><%= Event.where(id: attendance.event_id).last.name %></td>
                <td><%= attendance.attended %></td>
                <td><%= attendance.rsvp %></td>
                <% if Member.find_by(:email =>current_admin.email).admin? %>
                <td><%= link_to 'Show', attendance %></td>
                <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
                <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
              </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<br>
<% if Member.find_by(:email =>current_admin.email).admin? %>
  <%= link_to 'New Attendance', new_attendance_path, class:"btn btn-outline-dark btn-sm" %>
<%end %>

app/views/attendances/new.html.erb
<% if Member.find_by(:email =>current_admin.email).admin? %>
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back to Attendance', attendances_path, class:"btn btn-outline-dark btn-sm" %>
<% else %>
status: 403 'Forbidden'
<% end %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @member.fname %>
</p>

<p>
  <strong>Event:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Attended:</strong>
  <%= @attendance.attended %>
</p>

<p>
  <strong>Rsvp:</strong>
  <%= @attendance.rsvp %>
</p>
<% if Member.find_by(:email =>current_admin.email).admin? %>
<%= link_to 'Remove Attendance', @attendance, class:"btn btn-outline-dark btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
<br><br>

<%= link_to 'Edit', edit_attendance_path(@attendance), class:"btn btn-outline-dark btn-sm" %>
<%end %>
<%= link_to 'Back', attendances_path, class:"btn btn-outline-dark btn-sm" %>