config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :attendances do
    collection do
      match 'search' => 'attendances#search', via: [:get, :post], as: :search
    end
  end
  resources :dues do
    collection do
      match 'search' => 'dues#search', via: [:get, :post], as: :search
    end
  end
  resources :lineages
  resources :events
  resources :members

  resources :calendar, only: [:show],controller: :calendar
  
  #root "members#index"
  
  get "/members/:id" , to: "members#show"
  get "/lineages/:id" , to: "lineages#show"
  resources :members, :lineages, :events
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get '/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get '/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
    get "/members/:id" , to: "members#show"
    get "/lineages/:id" , to: "lineages#show"
    root "dashboards#show"
  end

  get "/events/:id", to: "events#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navpart.html.erb
<!-- As a heading -->
<% if admin_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link_to "Ol' Ags", members_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Members", members_path, class:" nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Events", events_path, class:" nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Lineages", lineages_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dues", dues_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Attendance", attendances_path, class:"nav-link" %>
          </li>
          <% if Member.find_by(:email =>current_admin.email).admin? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Add
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to 'New Member', new_member_path, class:"dropdown-item" %></li>
                <li><%= link_to 'New Event', new_event_path, class:"dropdown-item" %></li>
                <li><%= link_to 'New Lineage', new_lineage_path, class:"dropdown-item" %></li>
                <li><%= link_to 'New Dues', new_due_path, class:"dropdown-item" %></li>
                <li><%= link_to 'New Attendance', new_attendance_path, class:"dropdown-item" %></li>
              </ul>
            </li>
          <%end %>
        </ul>
        <form class="d-flex">
          <ul class="navbar-nav">
            <li class="nav-item me-2">
              <%= link_to "Sign Out", destroy_admin_session_path, class:"nav-link" %>
            </li>
          </ul>
        </form>
      </div>
    </div>
  </nav>
<%end%>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> %>

    <title>OlAgs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navpart' %>
    <br>
    <div class="container-fluid">
      <div class="p-3 mb-2 rounded bg-light text-dark">
    <%= yield %>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    
    <% if flash.any? %>
    <% flash.each do |key, value| -%>
      <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
    <% end -%>
  <% end %>
      </div>
    </div>
  </body>
</html>